import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
    plugins: [
        laravel({
            input: ['../src/main.tsx'],
            refresh: true,
        }),
        react(),
        tailwindcss(),
    ],
    resolve: {
        alias: {
            '@': path.resolve(__dirname, '../src'),
            'react': path.resolve(__dirname, 'node_modules/react'),
            'react-dom': path.resolve(__dirname, 'node_modules/react-dom'),
            'tailwindcss': path.resolve(__dirname, 'node_modules/tailwindcss'),
            'axios': path.resolve(__dirname, 'node_modules/axios'),
            '@hookform/resolvers': path.resolve(__dirname, 'node_modules/@hookform/resolvers'),
            '@radix-ui/react-accordion': path.resolve(__dirname, 'node_modules/@radix-ui/react-accordion'),
            '@radix-ui/react-alert-dialog': path.resolve(__dirname, 'node_modules/@radix-ui/react-alert-dialog'),
            '@radix-ui/react-aspect-ratio': path.resolve(__dirname, 'node_modules/@radix-ui/react-aspect-ratio'),
            '@radix-ui/react-avatar': path.resolve(__dirname, 'node_modules/@radix-ui/react-avatar'),
            '@radix-ui/react-checkbox': path.resolve(__dirname, 'node_modules/@radix-ui/react-checkbox'),
            '@radix-ui/react-collapsible': path.resolve(__dirname, 'node_modules/@radix-ui/react-collapsible'),
            '@radix-ui/react-context-menu': path.resolve(__dirname, 'node_modules/@radix-ui/react-context-menu'),
            '@radix-ui/react-dialog': path.resolve(__dirname, 'node_modules/@radix-ui/react-dialog'),
            '@radix-ui/react-dropdown-menu': path.resolve(__dirname, 'node_modules/@radix-ui/react-dropdown-menu'),
            '@radix-ui/react-hover-card': path.resolve(__dirname, 'node_modules/@radix-ui/react-hover-card'),
            '@radix-ui/react-label': path.resolve(__dirname, 'node_modules/@radix-ui/react-label'),
            '@radix-ui/react-menubar': path.resolve(__dirname, 'node_modules/@radix-ui/react-menubar'),
            '@radix-ui/react-navigation-menu': path.resolve(__dirname, 'node_modules/@radix-ui/react-navigation-menu'),
            '@radix-ui/react-popover': path.resolve(__dirname, 'node_modules/@radix-ui/react-popover'),
            '@radix-ui/react-progress': path.resolve(__dirname, 'node_modules/@radix-ui/react-progress'),
            '@radix-ui/react-radio-group': path.resolve(__dirname, 'node_modules/@radix-ui/react-radio-group'),
            '@radix-ui/react-scroll-area': path.resolve(__dirname, 'node_modules/@radix-ui/react-scroll-area'),
            '@radix-ui/react-select': path.resolve(__dirname, 'node_modules/@radix-ui/react-select'),
            '@radix-ui/react-separator': path.resolve(__dirname, 'node_modules/@radix-ui/react-separator'),
            '@radix-ui/react-slider': path.resolve(__dirname, 'node_modules/@radix-ui/react-slider'),
            '@radix-ui/react-slot': path.resolve(__dirname, 'node_modules/@radix-ui/react-slot'),
            '@radix-ui/react-switch': path.resolve(__dirname, 'node_modules/@radix-ui/react-switch'),
            '@radix-ui/react-tabs': path.resolve(__dirname, 'node_modules/@radix-ui/react-tabs'),
            '@radix-ui/react-toast': path.resolve(__dirname, 'node_modules/@radix-ui/react-toast'),
            '@radix-ui/react-toggle': path.resolve(__dirname, 'node_modules/@radix-ui/react-toggle'),
            '@radix-ui/react-toggle-group': path.resolve(__dirname, 'node_modules/@radix-ui/react-toggle-group'),
            '@radix-ui/react-tooltip': path.resolve(__dirname, 'node_modules/@radix-ui/react-tooltip'),
            '@tanstack/react-query': path.resolve(__dirname, 'node_modules/@tanstack/react-query'),
            'class-variance-authority': path.resolve(__dirname, 'node_modules/class-variance-authority'),
            'clsx': path.resolve(__dirname, 'node_modules/clsx'),
            'cmdk': path.resolve(__dirname, 'node_modules/cmdk'),
            'date-fns': path.resolve(__dirname, 'node_modules/date-fns'),
            'embla-carousel-react': path.resolve(__dirname, 'node_modules/embla-carousel-react'),
            'framer-motion': path.resolve(__dirname, 'node_modules/framer-motion'),
            'input-otp': path.resolve(__dirname, 'node_modules/input-otp'),
            'lucide-react': path.resolve(__dirname, 'node_modules/lucide-react'),
            'next-themes': path.resolve(__dirname, 'node_modules/next-themes'),
            'react-day-picker': path.resolve(__dirname, 'node_modules/react-day-picker'),
            'react-hook-form': path.resolve(__dirname, 'node_modules/react-hook-form'),
            'react-resizable-panels': path.resolve(__dirname, 'node_modules/react-resizable-panels'),
            'react-router-dom': path.resolve(__dirname, 'node_modules/react-router-dom'),
            'recharts': path.resolve(__dirname, 'node_modules/recharts'),
            'sonner': path.resolve(__dirname, 'node_modules/sonner'),
            'tailwind-merge': path.resolve(__dirname, 'node_modules/tailwind-merge'),
            'tailwindcss-animate': path.resolve(__dirname, 'node_modules/tailwindcss-animate'),
            'vaul': path.resolve(__dirname, 'node_modules/vaul'),
            'zod': path.resolve(__dirname, 'node_modules/zod'),
        },
        modules: [path.resolve(__dirname, 'node_modules'), 'node_modules'],
    },
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
